<?php

use yii\db\Migration;

class m170907_133342_insert_into_geo_country_table extends Migration
{
    public function safeUp()
    {
        $this->batchInsert('geo_country', ['id_continent', 'code', 'name_ru', 'name_en'], [
            [1, 'RW', 'Руанда', 'Rwanda'],
            [1, 'SO', 'Сомали', 'Somalia'],
            [2, 'YE', 'Йемен', 'Yemen'],
            [2, 'IQ', 'Ирак', 'Iraq'],
            [2, 'SA', 'Саудовская Аравия', 'Saudi Arabia'],
            [2, 'IR', 'Иран', 'Iran'],
            [3, 'CY', 'Кипр', 'Cyprus'],
            [1, 'TZ', 'Танзания', 'Tanzania'],
            [2, 'SY', 'Сирийская Арабская Республика', 'Syria'],
            [2, 'AM', 'Армения', 'Armenia'],
            [1, 'KE', 'Кения', 'Kenya'],
            [1, 'CD', 'Заир', 'Congo'],
            [1, 'DJ', 'Джибути', 'Djibouti'],
            [1, 'UG', 'Уганда', 'Uganda'],
            [1, 'CF', 'ЦАР', 'Central African Republic'],
            [1, 'SC', 'Сейшельские о-ва', 'Seychelles'],
            [2, 'JO', 'Иордания', 'Hashemite Kingdom of Jordan'],
            [2, 'LB', 'Ливан', 'Lebanon'],
            [2, 'KW', 'Кувейт', 'Kuwait'],
            [2, 'OM', 'Оман', 'Oman'],
            [2, 'QA', 'Катар', 'Qatar'],
            [2, 'BH', 'Бахрейн', 'Bahrain'],
            [2, 'AE', 'ОАЭ', 'United Arab Emirates'],
            [2, 'IL', 'Израиль', 'Israel'],
            [2, 'TR', 'Турция', 'Turkey'],
            [1, 'ET', 'Эфиопия', 'Ethiopia'],
            [1, 'ER', 'Эритрея', 'Eritrea'],
            [1, 'EG', 'Египет', 'Egypt'],
            [1, 'SD', 'Судан', 'Sudan'],
            [3, 'GR', 'Греция', 'Greece'],
            [1, 'BI', 'Бурунди', 'Burundi'],
            [3, 'EE', 'Эстония', 'Estonia'],
            [3, 'LV', 'Латвия', 'Latvia'],
            [2, 'AZ', 'Азербайджан', 'Azerbaijan'],
            [3, 'LT', 'Литва', 'Republic of Lithuania'],
            [3, 'SJ', 'Свальбард и Ян-Майен', 'Svalbard and Jan Mayen'],
            [2, 'GE', 'Грузия', 'Georgia'],
            [3, 'MD', 'Молдова', 'Republic of Moldova'],
            [3, 'BY', 'Беларусь', 'Belarus'],
            [3, 'FI', 'Финляндия', 'Finland'],
            [3, 'AX', 'Аланды', 'Åland'],
            [3, 'UA', 'Украина', 'Ukraine'],
            [3, 'MK', 'Македония', 'Macedonia'],
            [3, 'HU', 'Венгрия', 'Hungary'],
            [3, 'BG', 'Болгария', 'Bulgaria'],
            [3, 'AL', 'Албания', 'Albania'],
            [3, 'PL', 'Польша', 'Poland'],
            [3, 'RO', 'Румыния', 'Romania'],
            [3, 'XK', 'Косово', 'Kosovo'],
            [1, 'ZW', 'Зимбабве', 'Zimbabwe'],
            [1, 'ZM', 'Замбия', 'Zambia'],
            [1, 'KM', 'Коморские о-ва', 'Comoros'],
            [1, 'MW', 'Малави', 'Malawi'],
            [1, 'LS', 'Лесото', 'Lesotho'],
            [1, 'BW', 'Ботсвана', 'Botswana'],
            [1, 'MU', 'Маврикий', 'Mauritius'],
            [1, 'SZ', 'Свазиленд', 'Swaziland'],
            [1, 'RE', 'Реюньон', 'Réunion'],
            [1, 'ZA', 'ЮАР', 'South Africa'],
            [1, 'YT', 'Майотта', 'Mayotte'],
            [1, 'MZ', 'Мозамбик', 'Mozambique'],
            [1, 'MG', 'Мадагаскар', 'Madagascar'],
            [2, 'AF', 'Афганистан', 'Afghanistan'],
            [2, 'PK', 'Пакистан', 'Pakistan'],
            [2, 'BD', 'Бангладеш', 'Bangladesh'],
            [2, 'TM', 'Туркменистан', 'Turkmenistan'],
            [2, 'TJ', 'Таджикистан', 'Tajikistan'],
            [2, 'LK', 'Шри-Ланка', 'Sri Lanka'],
            [2, 'BT', 'Бутан', 'Bhutan'],
            [2, 'IN', 'Индия', 'India'],
            [2, 'MV', 'Мальдивские о-ва', 'Maldives'],
            [2, 'IO', 'Британская территория в Индийском океане', 'British Indian Ocean Territory'],
            [2, 'NP', 'Непал', 'Nepal'],
            [2, 'MM', 'Мьянма', 'Myanmar [Burma]'],
            [2, 'UZ', 'Узбекистан', 'Uzbekistan'],
            [2, 'KZ', 'Казахстан', 'Kazakhstan'],
            [2, 'KG', 'Кыргызстан', 'Kyrgyzstan'],
            [4, 'TF', 'Французские Южные Территории', 'French Southern Territories'],
            [2, 'CC', 'Кокосовые о-ва', 'Cocos [Keeling] Islands'],
            [5, 'PW', 'Палау', 'Palau'],
            [2, 'VN', 'Вьетнам', 'Vietnam'],
            [2, 'TH', 'Тайланд', 'Thailand'],
            [2, 'ID', 'Индонезия', 'Indonesia'],
            [2, 'LA', 'Лаос', 'Laos'],
            [2, 'TW', 'Тайвань', 'Taiwan'],
            [2, 'PH', 'Филиппины', 'Philippines'],
            [2, 'MY', 'Малайзия', 'Malaysia'],
            [2, 'CN', 'Китай', 'China'],
            [2, 'HK', 'Гонконг', 'Hong Kong'],
            [2, 'BN', 'Бруней Даруссалам', 'Brunei'],
            [2, 'MO', 'Макао', 'Macao'],
            [2, 'KH', 'Камбоджа', 'Cambodia'],
            [2, 'KR', 'Южная Корея', 'Republic of Korea'],
            [2, 'JP', 'Япония', 'Japan'],
            [2, 'KP', 'Северная Корея', 'North Korea'],
            [2, 'SG', 'Сингапур', 'Singapore'],
            [5, 'CK', 'Острова Кука', 'Cook Islands'],
            [5, 'TL', 'Восточный Тимор', 'East Timor'],
            [3, 'RU', 'Россия', 'Russia'],
            [2, 'MN', 'Монголия', 'Mongolia'],
            [5, 'AU', 'Австралия', 'Australia'],
            [2, 'CX', 'Остров Рождества', 'Christmas Island'],
            [5, 'MH', 'Маршалловы о-ва', 'Marshall Islands'],
            [5, 'FM', 'Микронезия', 'Federated States of Micronesia'],
            [5, 'PG', 'Папуа – Новая Гвинея', 'Papua New Guinea'],
            [5, 'SB', 'Соломонские острова', 'Solomon Islands'],
            [5, 'TV', 'Тувалу', 'Tuvalu'],
            [5, 'NR', 'Науру', 'Nauru'],
            [5, 'VU', 'Вануату', 'Vanuatu'],
            [5, 'NC', 'Новая Каледония', 'New Caledonia'],
            [5, 'NF', 'Остров Норфолк', 'Norfolk Island'],
            [5, 'NZ', 'Новая Зеландия', 'New Zealand'],
            [5, 'FJ', 'Фиджи', 'Fiji'],
            [1, 'LY', 'Ливия', 'Libya'],
            [1, 'CM', 'Камерун', 'Cameroon'],
            [1, 'SN', 'Сенегал', 'Senegal'],
            [1, 'CG', 'Конго', 'Republic of the Congo'],
            [3, 'PT', 'Португалия', 'Portugal'],
            [1, 'LR', 'Либерия', 'Liberia'],
            [1, 'CI', 'Кот-д\'\'Ивуар', 'Ivory Coast'],
            [1, 'GH', 'Гана', 'Ghana'],
            [1, 'GQ', 'Экваториальная Гвинея', 'Equatorial Guinea'],
            [1, 'NG', 'Нигерия', 'Nigeria'],
            [1, 'BF', 'Буркина Фасо', 'Burkina Faso'],
            [1, 'TG', 'Того', 'Togo'],
            [1, 'GW', 'Гвинея-Биссау', 'Guinea-Bissau'],
            [1, 'MR', 'Мавритания', 'Mauritania'],
            [1, 'BJ', 'Бенин', 'Benin'],
            [1, 'GA', 'Габон', 'Gabon'],
            [1, 'SL', 'Сьерра-Леоне', 'Sierra Leone'],
            [1, 'ST', 'Сан-Томе и Принсипе', 'São Tomé and Príncipe'],
            [3, 'GI', 'Гибралтар', 'Gibraltar'],
            [1, 'GM', 'Гамбия', 'Gambia'],
            [1, 'GN', 'Гвинея', 'Guinea'],
            [1, 'TD', 'Чад', 'Chad'],
            [1, 'NE', 'Нигер', 'Niger'],
            [1, 'ML', 'Мали', 'Mali'],
            [1, 'EH', 'Западная Сахара', 'Western Sahara'],
            [1, 'TN', 'Тунис', 'Tunisia'],
            [3, 'ES', 'Испания', 'Spain'],
            [1, 'MA', 'Марокко', 'Morocco'],
            [3, 'MT', 'Мальта', 'Malta'],
            [1, 'DZ', 'Алжир', 'Algeria'],
            [3, 'FO', 'Фарерские о-ва', 'Faroe Islands'],
            [3, 'DK', 'Дания', 'Denmark'],
            [3, 'IS', 'Исландия', 'Iceland'],
            [3, 'GB', 'Великобритания', 'United Kingdom'],
            [3, 'CH', 'Швейцария', 'Switzerland'],
            [3, 'SE', 'Швеция', 'Sweden'],
            [3, 'NL', 'Нидерланды', 'Netherlands'],
            [3, 'AT', 'Австрия', 'Austria'],
            [3, 'BE', 'Бельгия', 'Belgium'],
            [3, 'DE', 'Германия', 'Germany'],
            [3, 'LU', 'Люксембург', 'Luxembourg'],
            [3, 'IE', 'Ирландия', 'Ireland'],
            [3, 'MC', 'Монако', 'Monaco'],
            [3, 'FR', 'Франция', 'France'],
            [3, 'AD', 'Андорра', 'Andorra'],
            [3, 'LI', 'Лихтенштейн', 'Liechtenstein'],
            [3, 'JE', 'Джерси', 'Jersey'],
            [3, 'IM', 'Мэн, о-в', 'Isle of Man'],
            [3, 'GG', 'Гернси', 'Guernsey'],
            [3, 'SK', 'Словакия', 'Slovak Republic'],
            [3, 'CZ', 'Чешская Республика', 'Czechia'],
            [3, 'NO', 'Норвегия', 'Norway'],
            [3, 'VA', 'Ватикан', 'Vatican City'],
            [3, 'SM', 'Сан-Марино', 'San Marino'],
            [3, 'IT', 'Италия', 'Italy'],
            [3, 'SI', 'Словения', 'Slovenia'],
            [3, 'ME', 'Черногория', 'Montenegro'],
            [3, 'HR', 'Хорватия', 'Croatia'],
            [3, 'BA', 'Босния', 'Bosnia and Herzegovina'],
            [1, 'AO', 'Ангола', 'Angola'],
            [1, 'NA', 'Намибия', 'Namibia'],
            [1, 'SH', 'Остров Святой Елены', 'Saint Helena'],
            [6, 'BB', 'Барбадос', 'Barbados'],
            [1, 'CV', 'Острова Зеленого Мыса', 'Cape Verde'],
            [7, 'GY', 'Гайана', 'Guyana'],
            [7, 'GF', 'Французская Гвиана', 'French Guiana'],
            [7, 'SR', 'Суринам', 'Suriname'],
            [6, 'PM', 'Сен-Пьер и Микелон', 'Saint Pierre and Miquelon'],
            [6, 'GL', 'Гренландия', 'Greenland'],
            [7, 'PY', 'Парагвай', 'Paraguay'],
            [7, 'UY', 'Уругвай', 'Uruguay'],
            [7, 'BR', 'Бразилия', 'Brazil'],
            [7, 'FK', 'Фолклендские о-ва', 'Falkland Islands'],
            [4, 'GS', 'Южная Джорджия и Южные Сандвичевы Острова', 'South Georgia and the South Sandwich Islands'],
            [6, 'JM', 'Ямайка', 'Jamaica'],
            [6, 'DO', 'Доминиканская Республика', 'Dominican Republic'],
            [6, 'CU', 'Куба', 'Cuba'],
            [6, 'MQ', 'Мартиника', 'Martinique'],
            [6, 'BS', 'Багамы', 'Bahamas'],
            [6, 'BM', 'Бермудские о-ва', 'Bermuda'],
            [6, 'AI', 'Ангилья', 'Anguilla'],
            [6, 'TT', 'Тринидад и Тобаго', 'Trinidad and Tobago'],
            [6, 'KN', 'Сент-Киттс и Невис', 'Saint Kitts and Nevis'],
            [6, 'DM', 'Остров Доминика', 'Dominica'],
            [6, 'AG', 'Антигуа и Барбуда', 'Antigua and Barbuda'],
            [6, 'LC', 'Сент-Люсия', 'Saint Lucia'],
            [6, 'TC', 'Острова Тёркс и Кайкос', 'Turks and Caicos Islands'],
            [6, 'AW', 'Аруба', 'Aruba'],
            [6, 'VG', 'Британские Виргинские о-ва', 'British Virgin Islands'],
            [6, 'VC', 'Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines'],
            [6, 'MS', 'Монсеррат', 'Montserrat'],
            [6, 'MF', 'Остров Святого Мартина', 'Saint Martin'],
            [6, 'BL', 'Остров Святого Бартоломея', 'Saint-Barthélemy'],
            [6, 'GP', 'Гваделупа', 'Guadeloupe'],
            [6, 'GD', 'Гренада', 'Grenada'],
            [6, 'KY', 'Каймановы Острова', 'Cayman Islands'],
            [6, 'BZ', 'Белиз', 'Belize'],
            [6, 'SV', 'Сальвадор', 'El Salvador'],
            [6, 'GT', 'Гватемала', 'Guatemala'],
            [6, 'HN', 'Гондурас', 'Honduras'],
            [6, 'NI', 'Никарагуа', 'Nicaragua'],
            [6, 'CR', 'Коста-Рика', 'Costa Rica'],
            [7, 'VE', 'Венесуэла', 'Venezuela'],
            [7, 'EC', 'Эквадор', 'Ecuador'],
            [7, 'CO', 'Колумбия', 'Colombia'],
            [6, 'PA', 'Панама', 'Panama'],
            [6, 'HT', 'Гаити', 'Haiti'],
            [7, 'AR', 'Аргентина', 'Argentina'],
            [7, 'CL', 'Чили', 'Chile'],
            [7, 'BO', 'Боливия', 'Bolivia'],
            [7, 'PE', 'Перу', 'Peru'],
            [6, 'MX', 'Мексика', 'Mexico'],
            [5, 'PF', 'Французская Полинезия', 'French Polynesia'],
            [5, 'PN', 'Питкэрн', 'Pitcairn Islands'],
            [5, 'KI', 'Кирибати', 'Kiribati'],
            [5, 'TK', 'Токелау', 'Tokelau'],
            [5, 'TO', 'Тонга', 'Tonga'],
            [5, 'WF', 'Уоллис и Футуна', 'Wallis and Futuna'],
            [5, 'WS', 'Самоа', 'Samoa'],
            [5, 'NU', 'Ниуе', 'Niue'],
            [5, 'MP', 'Северные Марианские о-ва', 'Northern Mariana Islands'],
            [5, 'GU', 'Гуам', 'Guam'],
            [6, 'PR', 'Пуэрто-Рико', 'Puerto Rico'],
            [6, 'VI', 'Виргинские о-ва (США)', 'U.S. Virgin Islands'],
            [5, 'UM', 'Внешние малые острова (США)', 'U.S. Minor Outlying Islands'],
            [5, 'AS', 'Американское Самоа', 'American Samoa'],
            [6, 'CA', 'Канада', 'Canada'],
            [6, 'US', 'США', 'United States'],
            [2, 'PS', 'Палестинские территории', 'Palestine'],
            [3, 'RS', 'Сербия', 'Serbia'],
            [4, 'AQ', 'Антарктида', 'Antarctica'],
            [6, 'SX', 'Синт-Мартен', 'Sint Maarten'],
            [6, 'CW', 'Кюрасао', 'Curaçao'],
            [6, 'BQ', 'Бонайре, Синт-Эстатиус и Саба', 'Bonaire, Sint Eustatius, and Saba'],
            [1, 'SS', 'Южный Судан', 'South Sudan'],
        ]);
        
        $this->execute('UPDATE `geo_country` SET `created_at`=NOW(), `updated_at`=NOW() WHERE `code` IS NOT NULL');
    }

    public function safeDown()
    {
        $this->execute('SET FOREIGN_KEY_CHECKS=0');
        $this->truncateTable('geo_country');
        $this->execute('SET FOREIGN_KEY_CHECKS=1');
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m170907_133342_insert_into_geo_country_table cannot be reverted.\n";

        return false;
    }
    */
}
